services:
  node1:
    build:
      context: .
    environment:
      PORT: "8080"
      NODE_ID: "node-1"
      ROLE: "replica"
      MODE: "leaderless"
      N: "5"
      W: "5"
      R: "1"
      PEER_ADDRS: "http://node2:8080,http://node3:8080,http://node4:8080,http://node5:8080"
    ports:
      - "8080:8080"

  node2:
    build:
      context: .
    environment:
      PORT: "8080"
      NODE_ID: "node-2"
      ROLE: "replica"
      MODE: "leaderless"
      N: "5"
      W: "5"
      R: "1"
      PEER_ADDRS: "http://node1:8080,http://node3:8080,http://node4:8080,http://node5:8080"
    ports:
      - "8081:8080"

  node3:
    build:
      context: .
    environment:
      PORT: "8080"
      NODE_ID: "node-3"
      ROLE: "replica"
      MODE: "leaderless"
      N: "5"
      W: "5"
      R: "1"
      PEER_ADDRS: "http://node1:8080,http://node2:8080,http://node4:8080,http://node5:8080"
    ports:
      - "8082:8080"

  node4:
    build:
      context: .
    environment:
      PORT: "8080"
      NODE_ID: "node-4"
      ROLE: "replica"
      MODE: "leaderless"
      N: "5"
      W: "5"
      R: "1"
      PEER_ADDRS: "http://node1:8080,http://node2:8080,http://node3:8080,http://node5:8080"
    ports:
      - "8083:8080"

  node5:
    build:
      context: .
    environment:
      PORT: "8080"
      NODE_ID: "node-5"
      ROLE: "replica"
      MODE: "leaderless"
      N: "5"
      W: "5"
      R: "1"
      PEER_ADDRS: "http://node1:8080,http://node2:8080,http://node3:8080,http://node4:8080"
    ports:
      - "8084:8080"
