FROM --platform=$BUILDPLATFORM public.ecr.aws/docker/library/golang:1.25.8-alpine3.23 AS build

ARG TARGETOS=linux
ARG TARGETARCH=amd64

RUN apk add --no-cache git ca-certificates

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} \
    go build -ldflags="-s -w" -o /out/processor ./cmd/processor

FROM scratch

COPY --from=build /out/processor /app/processor
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

ENTRYPOINT ["/app/processor"]
