FROM golang:latest

WORKDIR /app

# Copy go mod/sum from the mapreduce directory
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code
COPY splitter.go ./

# Build the splitter
RUN go build -o /server splitter.go

EXPOSE 8080

CMD ["/server"]

