FROM golang:latest

WORKDIR /app

# Copy go mod/sum from the mapreduce directory
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code
COPY reducer.go ./

# Build the reducer
RUN go build -o /server reducer.go

EXPOSE 8082

CMD ["/server"]

